export const actionTypes = {
  PRODUCTS_FETCHING: "PRODUCTS_FETCHING",
  PRODUCTS_FETCH_SUCCESS: "PRODUCTS_FETCH_SUCCESS",
  PRODUCTS_FETCH_FAILURE: "PRODUCTS_FETCH_FAILURE",
  PRODUCT_REDEEM_FAILURE: "PRODUCTS_REDEEM_FAILURE",
  PRODUCT_REDEEM_SUCCESS: "PRODUCT_REDEEM_SUCCESS",
  PRODUCT_POSTING: "PRODUCT_POSTING",
  PRODUCT_SEARCH_FILTER: "PRODUCT_SEARCH_FILTER"
};
