export const userActionTypes = {
  USER_FETCHING: "USER_FETCHING",
  USER_FETCH_SUCCESS: "USER_FETCH_SUCCESS",
  USER_FETCH_FAILURE: "USER_FETCH_FAILURE",
  USER_ADD_CREDITS_SUCCESS: "USER_ADD_CREDITS_SUCCESS",
  USER_ADD_CREDITS_FAILURE: "USER_ADD_CREDITS_FAILURE",
  USER_GET_HISTORY_SUCCESS: "USER_GET_HISTORY_SUCCESS",
  USER_GET_HISTORY_FAILURE: "USER_GET_HISTORY_FAILURE",
  USER_GET_HISTORY_FAILURE: "USER_GET_HISTORY_FAILURE"
};
